### ISSUE TITLE
[Feature Request] Core for Wii/Wii U?

### ISSUE THREAD

**Issue by Cee123** [libretro/picodrive#109]
Hi there, just wondering why this core is not available on Retroarch for Wii. Any chance it could be made to work on the Wii? Thanks.

**Comment by Cee123** [comment]
I'd like to test out some 32X games to see how well they run on Wii/Wii U.

**Comment by irixxxx** [comment]
Big endian host CPUs are basically supported with core version 1.98. Is anybody out there able to build a Wii version and do some basic testing?

**Comment by Cee123** [comment]
> 
> 
> Big endian host CPUs are basically supported with core version 1.98. Is anybody out there able to build a Wii version and do some basic testing?

Yeah that's what I was wondering. I was trying to build it myself for the Wii and Wii U but it just gave me a bunch of error messages. Wasn't successful in building it.

**Comment by irixxxx** [comment]
There's a tentative patch in my repo to compile for ngc/wii/wiiu.

**Comment by irixxxx** [comment]
I've verified basic function with the dolphin emulator. The changes are merged into libretro, so you can give it a try.

**Comment by Edu789** [comment]
I tested the build last night and found the following errors:

Sega CD and 32x when starting the game from the Dsi screen.
Master system the D-pad does not work.
Genesis only works with analogues, the other buttons do not.

**Comment by Cee123** [comment]
> 
> 
> I tested the build last night and found the following errors:
> 
> Sega CD and 32x when starting the game from the Dsi screen.
> Master system the D-pad does not work.
> Genesis only works with analogues, the other buttons do not.

Sounds like it has the input bitmask issue that all the other cores were having, where the controls were not responding. This fix probably needs to be incorporated as well.
https://github.com/libretro/RetroArch/issues/11217

**Comment by Cee123** [comment]
> 
> 
> I've verified basic function with the dolphin emulator. The changes are merged into libretro, so you can give it a try.

That's awesome. Thank you! Will be interesting to see how well 32X runs on the Wii/Wii U.

**Comment by Cee123** [comment]
Master System, Mega Drive and Game Gear work using the core (except the controls) but 32X crash dumps on the Wii.
