### ISSUE TITLE
[Android] Can't run MEGA CD 32X game

### ISSUE THREAD

**Issue by duskgao** [libretro/picodrive#11]
I test 'corpse killer',a sega cd game need 32x,everything is ok before start menu,it just stuck ...

**Comment by sergiobenrocha2** [comment]
Upstream supports it. Needs to rebase/merge in some point

**Comment by sergiobenrocha2** [comment]
Related: https://github.com/notaz/picodrive/issues/57

**Comment by irixxxx** [comment]
Closed for obsolescence. Much has changed in the last 6 yrs. It seems to work now.
