### ISSUE TITLE
Disk swapping feels "weird" with recent RetroArch Disk Control menu changes.

### ISSUE THREAD

**Issue by bslenul** [libretro/picodrive#114]
Hey! Since the recent changes in the Disk Control menu the disc swapping in PicoDrive can be a bit confusing, here's an example with `Sherlock Holmes - Consulting Detective Vol. II` (another easy way to test is to simply load disc 2 of Night Trap, after the logo it will ask to insert disc 1):

* Load disc 1 .cue file and select PicoDrive.
* Select the last case, it will ask to insert disc 2.
* Go to `Quick Menu > Disk Control`.
* And that's where it gets weird, the virtual tray is already open and you can't select disc 2 .cue directly.
* So you have to `Insert Disk` to close the tray again, which resumes the game.
* Re-open `Disk Control` menu.
* Click `Load New Disk`, and finally load disc 2 .cue!

That will probably confuse a lot of new users, it doesn't make sense to insert a disc which was already inserted, then re-open RA menu to load a new disc :p 

Here's the process in action (using latest RA nightly and PicoDrive): https://www.youtube.com/watch?v=TRRygoBUSNM  
Btw, I noticed that I was using BIOS 2.00 in the video, so just in case I tried with 1.10 which is the one recommended in the docs page, but that didn't change anything.

I made a feature request for .m3u support a while ago (#89), idk how hard that would be to implement but IMO it would be probably more user friendly since you could directly change "Disk Index" and then "Insert Disk".

Or just make it so the core doesn't auto-eject tray, so you can have acces to the "Load New Disk" right away.

**Comment by klepp0906** [comment]
gensplus just had m3u and disk control added today.

leaves this guy as the odd man out which is problematic if for no other reason that its preventing an entire scd library conversion/multidisc conversion to chd/m3u over the 32x cd games.  Even when kept separate that darn farenheit game requiring the key disc is gonna require the standard scd variant even kept/used in a picodrive compatible format. 

ever closer though, ever closer : p

**Comment by jdgleaver** [comment]
@bslenul Once this gets merged, could you please confirm that it solves the problem? https://github.com/libretro/RetroArch/pull/10865

**Comment by bslenul** [comment]
You're everywhere :x 

Tested on both Sherlock Holmes and Night Trap, works like a charm as usual: https://streamable.com/8x5uhu

Thank you, again :D

**Comment by jdgleaver** [comment]
Again, you're very welcome!

Thanks for testing (the video is a really nice touch!)
