### ISSUE TITLE
Sega 32X Segfault.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [libretro/picodrive#115]
The current Sega32X Module segfaults as follows.
Failed to open /opt/var/public/roms/sega32x/After Burner Complete (32X) (U) [!].srm: No such file or directory
Illegal instruction (core dumped)

**Comment by Zombie-Ryushu** [comment]
Attempting to build from master.zip yields the following.

libpicofe is missing, please run 'git submodule update --init'

**Comment by irixxxx** [comment]
I think none of this is really an issue:
- you can't directly open .srm-files. Those are files to store save-RAM contents that's inside some cartridges. Open the ROM image file instead.
- the solution to the 2nd comment is given by the configure output - run 'git submodule update --init' before configuring. Moreover, configuring isn't needed for libretro: 'make -f Makefile.libretro platform=<select platform here>' to compile.
