### ISSUE TITLE
Game sound (Tempo) with wheezing

### ISSUE THREAD

**Issue by AlanRibas** [libretro/picodrive#122]
I was testing a game at the core of RetroArch called PicoDrive.
I noticed that the sound has quite a sizzle. Some parts of the game less and others more.
I recorded a video of the specific part where you can hear the wheezing at the end of the video.

Is this bad sound a problem with the PicoDrive core? Or is it something solved with configuration in RetroArch?

https://www.youtube.com/watch?v=SEhAOjLuRWA

**Comment by irixxxx** [comment]
I believe this has been solved with the current master. Should be tested again and subsequently closed if fixed.

**Comment by irixxxx** [comment]
Fixed with current core
