### ISSUE TITLE
6 Button Mapping Is Broken

### ISSUE THREAD

**Issue by newoski** [libretro/picodrive#14]
RetroKeyboard 6 button functionality currently does not work via RetroArch 1.2.2 or the latest nightlies. I have tested on both. I have my core options set to 6 buttons for both inputs and have also confirmed the issue with others on the retroarch irc channel. 

If you need anything else to help troubleshoot / fix, please let me know.

**Comment by Yardl3y** [comment]
I have the same exact problem. Seems like a simple fix, would be great if someone can take a look at it!

**Comment by newoski** [comment]
Is this a complicated fix?

**Comment by newoski** [comment]
Any updates?

**Comment by unixunion** [comment]
+1

**Comment by newoski** [comment]
This was user error on my part. I was testing Mortal Kombat II. While the game does support 6 Button controllers, they need to be enabled via the in-game Options menu. There is no bug. Everything works.
