### ISSUE TITLE
half screen with CPU NTSC filter

### ISSUE THREAD

**Issue by eadmaster** [libretro/picodrive#15]
When using the core with a NTSC CPU filter, the screen is scaled wrongly (only half screen is filled horizontally).

This is probably related to [this old issue](https://github.com/libretro/RetroArch/issues/5).

EDIT: a possible workaround is using the [NTSC shader](https://github.com/libretro/common-shaders/tree/master/ntsc), but it is slow on some GPUs and too noisy for my tastes...

**Comment by CyberLabSystems** [comment]
This does not occur if you use the new
 Blargg_NTSC_Genesis_Composite_CyberLab_Special_Edition.filt 

aka
 Blargg_SNES_Custom_Psuedo_MD_Composite 

or
 Blargg_NTSC_Genesis_S-Video_CyberLab_Special_Edition.filt 

aka
 Blargg_SNES_Custom_Psuedo_MD_S-Video.filt video filter presets.

Or
 Blargg_NTSC_Turbo_Duo_SNES_PSX_Composite_CyberLab_Special_Edition.filt 

aka

Blargg_SNES_Custom_Psuedo_PCE_PSX_SNES_COMPOSITE.filt

Blargg_NTSC_Turbo_Duo_SNES_PSX_S-Video_CyberLab_Special_Edition.filt

aka

Blargg_SNES_Custom_Psuedo_PCE_PSX_SNES_S-Video.filt

or

Blargg_NTSC_Turbo_Duo_SNES_PSX_RGB_CyberLab_Special_Edition.filt

aka

Blargg_SNES_Custom_Psuedo_PCE_PSX_SNES_RGB.filt video filter presets.

It might be a good idea to confirm and mark this one as closed.

**Comment by eadmaster** [comment]
@CyberLabSystems: interesting filters pack, can you add them in the [main repo](https://github.com/libretro/RetroArch/tree/master/gfx/video_filters) so we will have them with all the ports?

Btw i've just verified [this PR](https://github.com/libretro/picodrive/pull/27) does not seem to fix this issue on Android.
