### ISSUE TITLE
[Wii] Mega Drive SRAM not working

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/picodrive#153]
Thanks for adding PicoDrive core on Wii!

## Reproduce

1. pick a game that creates initialises and tests SRAM on bootup
   eg. _New 3D Golf Simulation: Pebble Beach no Hatou_ (Japan, Mega Drive) or if it's easier to test use the Western release: _True Golf Classics: Pebble Beach Golf Links_ (NTSC-U, Genesis)

2. Run the game using libretro/picodrive core

## Expected

- Game should load to title screen without error

## Actual

- Game displays SRAM error screen and restarts

## Testing

- Wii RetroArch 1.9.2
- PicoDrive core is new to Wii so cannot test further back

## Notes

- Game loads fine with PicoDrive on other platforms (Windows, RA 1.9.2)
- Game loads fine with GenPlus emulator (Wii, RA 1.9.2)

**Comment by irixxxx** [comment]
fixed with 78c2237 in my repo

**Comment by gingerbeardman** [comment]
Thanks @irixxxx !

**Comment by gingerbeardman** [comment]
@twinaphex any chance this fix could be merged? many thanks!

It's not there as of 1.9.3

**Comment by irixxxx** [comment]
I try to do this in a more or less regular timeframe of about once a month if "important" changes or enough of small change are there. Next merge should take place at the end of this month.

**Comment by gingerbeardman** [comment]
Thank you @irixxxx my expectations are reset 👍

**Comment by irixxxx** [comment]
Sorry for that. My policy is to keep tickets open as long as the fix hasn't landed to prevent duplicates. So, you should expect this ticket (and possibly others which are fixed) to be closed after the merge from my repo.

**Comment by irixxxx** [comment]
merged into libretro

**Comment by gingerbeardman** [comment]
Many thanks
