### ISSUE TITLE
[PSP] Picodrive inverted colors

### ISSUE THREAD

**Issue by Harry7228** [libretro/picodrive#157]
Hi! Retroarch on PSP running Picodrive all colours are inverted.
I have tested with several games. They all show the 'inverted' color problem.

**Comment by irixxxx** [comment]
Can you make me a screenshot please?

**Comment by Harry7228** [comment]
![screenshot](https://user-images.githubusercontent.com/85024400/120085452-81ea0a80-c0d8-11eb-896f-2157a248a3fd.jpg)

**Comment by irixxxx** [comment]
ah ok, the BGR mode apparently isn't correct here.

**Comment by Harry7228** [comment]
Thanks for looking into this problem. I hope there will be a fix for it.

**Comment by irixxxx** [comment]
I reckon it's just the removal of the -DUSE_BGR565 in the psp section of libretro Makefile. It's just that I can't test it (no hw), and I didn't introduce that option. I've forwarded that question.

**Comment by irixxxx** [comment]
Hopefully fixed with f965a24

**Comment by irixxxx** [comment]
BTW, out of curiosity, have you used the 1.98 standalone build from my repo? Just wondering... it went there by accident, but if someone can confirm everything's working fine on the real thing (me having checked this only with ppsspp), I can leave the build for the next versions.

**Comment by Harry7228** [comment]
I have tested (on real hw) the latest build from the RetroArch nightly's, it is working great. This was the fix... Thanks.
