### ISSUE TITLE
rewind broken with some games

### ISSUE THREAD

**Issue by eadmaster** [libretro/picodrive#16]
The rewind feature seems broken in "Knuckles' Chaotix (32X) (JU) [!]" (and possibly other games?).
Btw savestates are working fine.

**Comment by irixxxx** [comment]
I know this has been long ago, but I recently revisited saving/loading emulation state and fixed several bugs. Since that's the base for rewind and run-ahead, @eadmaster could you possibly check this again?

**Comment by eadmaster** [comment]
sorry for the late reply, this seems to be fixed in the latest builds.
