### ISSUE TITLE
Knuckles Chaotix Graphical Glitch

### ISSUE THREAD

**Issue by TideGear** [libretro/picodrive#163]
During the player select screen, there's ugly graphical glitching.

Tested with the latest build of the PicoDrive core on RA for Android.

**Comment by irixxxx** [comment]
I assume you are talking about the data load screen?
Which game version did you use? Region code?

**Comment by TideGear** [comment]
> I assume you are talking about the data load screen?
> Which game version did you use? Region code?

No, it's the character selection screen. It's after the introductory stage where you rescue Espio (the purple one). You return to a base where you choose your character (the glitched screen), then there's a crane game where you choose a second character, then a level select screen.

I'm playing the US/Japan version.

**Comment by irixxxx** [comment]
fixed with e704c9b in my repo. fixed in libretro with the next merge.

**Comment by TideGear** [comment]
> fixed with [e704c9b](https://github.com/libretro/picodrive/commit/e704c9b913cd462ab57370bfe80fdffa8ed60ace) in my repo. fixed in libretro with the next merge.

You work fast! Thank you!

**Comment by TideGear** [comment]
> fixed with [e704c9b](https://github.com/libretro/picodrive/commit/e704c9b913cd462ab57370bfe80fdffa8ed60ace) in my repo. fixed in libretro with the next merge.

Did this fix increase performance requirements? I don't recall the Chaotix intro animation dropping frames.

**Comment by TideGear** [comment]
My mistake. I see now that the update isn't out yet, AND I should be using the 32-bit Retroarch for PicoDrive, not 64-bit.

**Comment by irixxxx** [comment]
I merged my repo master, hence you can give the next nightly a go.
