### ISSUE TITLE
Is it possible to improve sound quality on PS2?

### ISSUE THREAD

**Issue by Ever17lab** [libretro/picodrive#172]
Hey! Thanks a lot for you job!
Your core works on PS2 at full speed and it's one of the reason to use Retroarch on that platform.

But small sound crackling... Can you fix it, or suggest settings?

**Comment by irixxxx** [comment]
I think the sound crackling is a problem of retroarch, I can't here anything like that in a standalone version. However, there is a sound accuracy problem in the core, see RetroArch issue 12791.

**Comment by irixxxx** [comment]
fixed in my repo. Available in this repo after my next merge

**Comment by Ever17lab** [comment]
Nice ^_^

**Comment by irixxxx** [comment]
Oh, that was a while, sorry. But finally merged.
