### ISSUE TITLE
Core options are missing in recent builds on 64-bit Windows

### ISSUE THREAD

**Issue by haojiezhu** [libretro/picodrive#179]
It seems core options are completely missing now on Windows with recent builds of core file (tested nightly on buildbot and the one inside RetroArch 1.9.10 core packages). Android version doesn't seem to be affected.

![picodrive_new](https://user-images.githubusercontent.com/11336033/134402519-173524e4-abed-48a3-bf51-73c2d5cd3b9d.png)

Even if I manually edit "RetroArch\config\PicoDrive.opt" file, the core won't read it at all and is stuck with default settings (tested this by changing "picodrive_input1" to "6 button pad" and controls in "Super Street Fighter II: The New Challenger" still only have 3 buttons). The version from RetroArch 1.9.9 core packages (https://buildbot.libretro.com/stable/1.9.9/windows/x86_64/RetroArch_cores.7z) doesn't have this problem.

![picodrive_old](https://user-images.githubusercontent.com/11336033/134402546-a7a1ca27-a29a-429d-bd7b-73d5ca8286e4.png)

Update: Did more tests. 32-bit Windows version wasn't affected either.

**Comment by stuken** [comment]
Just submitted a pull request that should fix things. #180
