### ISSUE TITLE
Difficult to understand input descriptor for Master System

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/picodrive#19]
It's a little bit difficult to understand these input descriptor for Master System:

User 1 1 Start
User 1 2

User 2 1 Start
User 2 2

I have read "11" (eleven) in the first try. Maybe it could be better if it was User 1  "1" (Start)

@AkimanBengus

**Comment by AkimanBengus** [comment]
I understand what you mean but I wanted to stick as closed as the label on the Hardware
![master system controller](https://cloud.githubusercontent.com/assets/14359251/12975972/b977e4ee-d0c0-11e5-8d9f-855965d07667.jpg)

Here is 2 propositions:
Button prefix
![master system - button](https://cloud.githubusercontent.com/assets/14359251/12976001/fc11f93e-d0c0-11e5-9e96-9aca08d386cc.png)

btn prefix
![master system - btn](https://cloud.githubusercontent.com/assets/14359251/12976007/1029bdda-d0c1-11e5-8544-60a186b216c4.png)

Tell me guys, what you prefer and if this necessary to change it.

**Comment by sergiobenrocha2** [comment]
That first picture with "Button" is better I think.
