### ISSUE TITLE
[SMS][Feature] Hide left black border

### ISSUE THREAD

**Issue by Apaczer** [libretro/picodrive#190]
Kind request to add VIDEO option: "Hide Master System side border" for Left Border (to stretch and recenter the modified image).

Normally I would use image-adjustment shader or overlay, but those options aren't supported on OpenDingux devices with RetroArch and the Picodrive core is the fastest and most reliable of all cores on low-spec arm32 cpus (albeit other cores support titled feature).

**Comment by irixxxx** [comment]
added with 96948bd

**Comment by Apaczer** [comment]
Tested with few games on libretro_core & standalone - pixels look even and image is oriented as expetced (that is for keep_aspect_ratio = 1)

Thank you. Maybe we can have this optional for more `hardcore` users.
