### ISSUE TITLE
Amazing Spider-Man: Web of Fire (32X) Freezing Issues

### ISSUE THREAD

**Issue by Freakservo** [libretro/picodrive#210]
As of version 1.99-0a4ec83, Amazing Spider-Man: Web of Fire freezes.   Usually either on the title screen or within the first 10 seconds of play...But its occurrence rate is 100% on at least 20 tries (Shut-Down/Relaunch.  Resetting at any point initiates an instant-freeze, even when game is running).

This has been tested on both the latest RetroArch (1.12.0) and RALibretro (1.3.11).  Results are same on both.

**Comment by niuus** [comment]
> As of version 1.99-0a4ec83, Amazing Spider-Man: Web of Fire freezes. Usually either on the title screen or within the first 10 seconds of play...But its occurrence rate is 100% on at least 20 tries (Shut-Down/Relaunch. Resetting at any point initiates an instant-freeze, even when game is running).
> 
> This has been tested on both the latest RetroArch (1.12.0) and RALibretro (1.3.11). Results are same on both.

This happens to me. To trigger it, you need to have the second controller disabled in Core Options. Don't skip any of the intro screens or press anything. Should soft hang when you arrive to the title screen and Spiderman swings in. You will notice the "All Rights Reserved" gets stuck out of screen when scrolling.

Using Picodrive Wii, nightly build October-23.

**Comment by Freakservo** [comment]
Updated the core on both RetroArch and RALibretro (Should mention I'm using Windows 64bit builds) and enabled the second controller.  Tried a combination of both 3-and-6 button modes...In my experience, this gets by the title screen, but will still freeze during both the demo and actual gameplay.

**Comment by elessar38** [comment]
The same problem. The game freezes completely at random moments after launching.
Changing the settings does not help.

**Comment by irixxxx** [comment]
fixed with eb990fd
