### ISSUE TITLE
Version 1.99-97fa8bc not run Overdrive 2

### ISSUE THREAD

**Issue by Augusto7743** [libretro/picodrive#213]
Hello.
When trying run Overdrive 2 demo have an moment the emulation stop with black screen.
Only reporting.
Have an nice week.

**Comment by Augusto7743** [comment]
Thanks.

**Comment by irixxxx** [comment]
Merge from my repo.

**Comment by Augusto7743** [comment]
Tested. Now the Overdrive 2 run , but an few before of ending credits the sound is cut off.

**Comment by irixxxx** [comment]
Known bug, see irixxxx#25

**Comment by irixxxx** [comment]
Fixed, see irixxxx#25

**Comment by irixxxx** [comment]
merged into lr-picodrive.
