### ISSUE TITLE
Virtua Racing (MD) crashes at the finish line of a race (arm32)

### ISSUE THREAD

**Issue by CometHunter92** [libretro/picodrive#215]
At the commit https://github.com/libretro/picodrive/commit/7ab066aab84f15388a53433ea273420bcf917e00 , on an arm32 platform (RG35xx) crashes consistently at the finish line of a race. On arm64 platforms (Pi4, RG552, RG353) no issues. It's not mandatory to win the race, just finishing.

**Comment by CometHunter92** [comment]
It's a dynarec related issue, if it's disabled crash doesn't happen anymore.

**Comment by DrUm78** [comment]
@irixxxx I confirm, it crashes for me too on armv7 32-bit FunKey S handheld with the native port.

**Comment by irixxxx** [comment]
fixed with a80b0b4 in my repo. In lr-picodrive with the next merge.
