### ISSUE TITLE
Blackthorne broken sound/music

### ISSUE THREAD

**Issue by KamiLordus** [libretro/picodrive#217]
After the latest update, Blackthorne has broken sound/music. Already in the menu, the music breaks down, there are strange sounds, etc. In the game itself, I noticed that there is no gunshot sound at all.

Retroarch 1.15
Win11

**Comment by DrUm78** [comment]
Yep, the guilty is https://github.com/irixxxx/picodrive/commit/805fbe6faa2cc98821356828af5055f0cd6584bd, it also broke the display:
![image](https://github.com/libretro/picodrive/assets/46139740/2fbf5459-7779-4b1f-81a7-135f1e008307) ![image](https://github.com/libretro/picodrive/assets/46139740/bba8bc6d-fc61-4472-94dd-3f3260d2704a)

**Comment by irixxxx** [comment]
I already noticed that and have a fix for the intro music, but don't know if this works for your other problems as well. If you are able to compile the core yourself I could post the small fix here for you to try out.

**Comment by KamiLordus** [comment]
@irixxxx not only in the intro there is a problem. The music works in the game, but the sounds don't. You can't hear gunshots, picking up items, jumping, footsteps, etc.
@DrUm78 you're right, I didn't notice that. The image display is also broken.

**Comment by irixxxx** [comment]
Whatever, I found a fix for the intro. @DrUm78 has already tested it and it works through for him for the other problems too. So, in pico/32x/memory.c, change the THRESHOLD in line 62 from 9 to 11, and all is hopefully well again.

**Comment by KamiLordus** [comment]
@irixxxx could you add this fix for retroarch ?

**Comment by KamiLordus** [comment]
No problem :) I'm not that impatient.

**Comment by irixxxx** [comment]
compile a core from the repo or get the latest from https://git.libretro.com/libretro/picodrive/-/pipelines for testing.

**Comment by irixxxx** [comment]
According to reports from @DrUm78 and other I think this is fixed with f81718c

**Comment by KamiLordus** [comment]
Yes, the problem has been fixed. Thank you.
