### ISSUE TITLE
[Game Gear] Castle of Illusion - Inverted colors and corruption

### ISSUE THREAD

**Issue by retroNUC** [libretro/picodrive#218]
Inverted colors and corruption seen when attempting to run this game on latest version of Picodrive core across several platforms.

`Castle of Illusion Starring Mickey Mouse (USA, Europe, Brazil) (En)`

Tested on Android (aarch64, latest from the buildbot) and Miyoo Mini Plus (linux armv7a, included with OnionUI), same issue seen.

![Screenshot_20230712_013706_RetroArch (AArch64)](https://github.com/libretro/picodrive/assets/71151161/e05e6764-3a8d-4b27-b41b-fff90c751bfc)

![20230712_013908](https://github.com/libretro/picodrive/assets/71151161/782f2898-9f8f-43ec-9f0e-030d304c0355)

**Comment by irixxxx** [comment]
This game is actually not a real Gamegear game. It's an SMS game, running on the GG in SMS mode.

The SMS mode of the Gamegear is currently not supported. Not sure if I'm going to ever do this, since the gain is next to non-existent - just playing the original SMS version is giving you the same game.

**Comment by retroNUC** [comment]
Cool, no worries. For these games (found the list over on SMS Power), I can just set up per-game core options for that system type.

**Comment by irixxxx** [comment]
I've nonetheless included some checks to test for some 10 images needing the sms mode and run those as sms as a kludge.

**Comment by irixxxx** [comment]
Merged. Most titles requiring SMS mode should now be autodetected with ca206ba and c9076db.
