### ISSUE TITLE
Closing game = retroarch crash

### ISSUE THREAD

**Issue by KamiLordus** [libretro/picodrive#219]
After the latest update, closing any game crashes the entire retroarch.

RA 1.16
Picodrive 363ddaa6
Win 11

**Comment by irixxxx** [comment]
It seems to work fine under RA on linux. I additionally did a standalone ASAN run to see if there's any memory overwrite or leak, but nothing shows up with some random Megadrive titles. Can you confirm this is happening elsewhere (that is, not Windows)?

**Comment by KamiLordus** [comment]
Unfortunately not. I only use RA with windows 11.
I use Picodrive to emulate Sega 32X games.
I will only add that the previous version worked without any problems.
I leave the log of Blackthorne on and off on the 32X.
[retroarch__2023_08_11__14_06_03.log](https://github.com/libretro/picodrive/files/12321319/retroarch__2023_08_11__14_06_03.log)

**Comment by irixxxx** [comment]
It's only happening with 32x... "any" was a bit too imprecise ;-)

fixed with bccd883
