### ISSUE TITLE
M68k state saving unaligned store

### ISSUE THREAD

**Issue by bnister** [libretro/picodrive#222]
The u32 store at + 0x4e was causing an unaligned store exception for the MIPS build
https://github.com/libretro/picodrive/blob/570319349588288f64c676123244acdb0be33881/pico/sek.c#L224
It also overwrites part of the value at + 0x50
I believe this should be changed to s16 since it's not being loaded as u32
https://github.com/libretro/picodrive/blob/570319349588288f64c676123244acdb0be33881/pico/sek.c#L267

**Comment by irixxxx** [comment]
Indeed, you're right. Would you like to make a PR, or should I just fix it?

**Comment by bnister** [comment]
Whatever's less hassle. I suggest just fixing it then closing the issue

**Comment by irixxxx** [comment]
I've made a commit to my repo. In with the next merge (RSN).
