### ISSUE TITLE
32X CD games suddenly stopped working

### ISSUE THREAD

**Issue by mario-64** [libretro/picodrive#224]
After a recent lr-picodrive update (not sure which), my 32X CD games have suddenly stopped working. It never even gets to the CD splash screen where you press Start. They used to work fine and I haven’t changed anything with BIOS files or the game images.  Is CD support broken?

Rpi4 8GB

**Comment by irixxxx** [comment]
I've tried the 3 games I own, and they appear to work in a standalone version. That doesn't necessarily mean it's working in RA, but are you sure you didn't damage your setup somehow? BIOS files installed?
If so, please make a RA log and attach that.

**Comment by mario-64** [comment]
Thank you for checking. Is there a way to full reset my picodrive setup? Again, I haven't touched BIOS files or CD images in years. The only thing I've done was update packages in Retropie Setup.

**Comment by hizzlekizzle** [comment]
a log would indeed be helpful to identify what's actually failing.

**Comment by mario-64** [comment]
I've never tried to capture Retroarch log files. Let me see if I can figure out how that works on Retropie via RPI

**Comment by hizzlekizzle** [comment]
I don't know about Retropie, but as far as RetroArch itself is concerned:

> there are a few ways to get a log, but the easiest is to go to settings > log and set both logging verbosities to DEBUG and 'log to file' to ON. Do whatever it takes to reproduce the offending behavior and then close RetroArch (if needed). It will then create a log file in your 'log' directory, which you can open in a text editor. If you want us to take a look at it, copy/paste the log contents somewhere like pastebin.com and then post a link to it here (this is more convenient for people than having to download it and open it in our own text editors)

**Comment by irixxxx** [comment]
Not really. You could try to throw away the settings file and replace the BIOS files. I'm usually throwing away both the RA and LR-PicoDrive config files for good measure.

**Comment by mario-64** [comment]
Tried that. Also tried a complete uninstall and reinstall of lr-picodrive. Retroarch shows that the core sees the BIOS files so clearly that isn't the issue. None of my CD games will launch. I give up. Again, the only thing that changed is updating packages in Retropie. So either the current core can't play CD games or something is screwy with the current release of Retropie. I've spent way too much time on this already. Thanks for the input.

**Comment by irixxxx** [comment]
Be so good and make me the RA log output. It will definitely help to get more insight into the problem!

**Comment by mario-64** [comment]
If I get time I’ll create a brand new SD card image and see if it has the same issue.

**Comment by mario-64** [comment]
Ok so I started with a new SD card and imaged it with the rpi4 image, https://retropie.org.uk/download/
Upon first boot I copied over the BIOS files and games. Picodrive was v1.10.0.  Everything worked fine.
I then did a Retropie update of all packages which put Picodrive to v1.16.0. Once again, CD games no longer work. I tried to enable debug logging but the runcommand.log file doesn't really show anything other than the picodrive launch command.

**Comment by irixxxx** [comment]
That sounds like a real problem. Could you please do me the favour and follow this "generating logs via menu":
https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-via-menu
and post the resulting log file here? This might provide clues about what's going on here.

**Comment by mario-64** [comment]
That's exactly what I did already. Is there some other log file besides runcommand.log I should be checking?

**Comment by hizzlekizzle** [comment]
Yeah, you should have something like 'retroarch.log' (possibly with a date-stamp in the filename) in whatever directory is designated for 'logs', the path for which you can find by going to settings > directory in the RetroArch menu.

**Comment by mario-64** [comment]
I'm not familiar with Linux and cannot find any log file other than runcommand.log which has nothing of value. Perhaps the dev can investigate on their test system?
