### ISSUE TITLE
Update core to latest build

### ISSUE THREAD

**Issue by MinecraftMario27** [libretro/picodrive#225]
the latest build of PicoDrive is released

**Comment by irixxxx** [comment]
There's the irixxxx-merge branch for testing if you can compile one yourself.

@hizzlekizzle: Apparently the build bot is somehow not working, so I can't complete the merge. I'm not going to advance the master branch as long as I don't know at least the build is working ;-)

**Comment by irixxxx** [comment]
Merged.

**Comment by hizzlekizzle** [comment]
did it start working again? you were able to get it sorted?

**Comment by irixxxx** [comment]
I did nothing, it somehow was fixed after some hours.
