### ISSUE TITLE
CDDA audio output is silent in BIOS / Vita port

### ISSUE THREAD

**Issue by TheShadowRunner** [libretro/picodrive#226]
Trying to listen to games' cdda audio tracks in the Sega CD BIOS (USA) on RetroArch Vita port gives no sound.

The same tracks work perfectly in-game.
This seems to be solely impacting the Vita port  for some reason.

Picodrive Core version is. "1.99-unknown" in Vita port.
The nightly PC  port has Core version "pre-2.00-alpha3-d907d65" and it seems to be working ok there.
Could it be outdated ?

**Comment by irixxxx** [comment]
Yes, maybe. How about trying a more current version from the build bot, e.g. this is the latest compiled version as of now:
https://git.libretro.com/libretro/picodrive/-/pipelines/248169

**Comment by TheShadowRunner** [comment]
I tried the latest build of Picodrive Core (2.00-alpha3) but that's not it, still no audio output for cdda in bios.
It must be a Retroarch vita port issue..

**Comment by irixxxx** [comment]
Both Japanese and US BIOS for Sega CD 1 (the one with the CD drawer) do play music in BIOS on ARMv7 platforms for me, at least from CHD files. However of course not the 1st track since that's the binary code.
Which BIOS version have you used, and what's the file format of the sound files?

**Comment by TheShadowRunner** [comment]
I used US BIOS and audio files were in ReDump format (.bin).
Of course Track 1 (data) doesn't play.

**Comment by irixxxx** [comment]
There are several versions of the BIOS, for Sega CD 1 and 2. The version should be visible on the primary BIOS screen.

**Comment by TheShadowRunner** [comment]
Sure, it's:
bios_CD_U.bin | 2efd74e3232ff260e371b99f84024f7f

**Comment by irixxxx** [comment]
fixed with 4aaedc8. In with the next merge, due soon with the next alpha/beta
