### ISSUE TITLE
Audio issues with Sonic 1 & 2 on Genesis

### ISSUE THREAD

**Issue by RobotLimeLtd** [libretro/picodrive#228]
Version:  pre-2.0.0-beta2-ad93670

Sonic the Hedgehog 2 on Genesis has severe audio issues - no music or sound effects.  I was previously on pre-2.0.0-alpha where it would randomly have no music on reload of the rom.  In this latest version, the audio is completely silent no matter how many times I reload.

The original Sonic The Hedgehog (Japanese edition) also has random audio problems in Marble Zone, where one of the instrument channels fails.

I’m not sure why Retroarch’s online updater has given me a pre-release version… is there a way to downgrade and only accept release versions?

**Comment by irixxxx** [comment]
If you can compile by yourself, try beta3 from my repository please. That should fix this.

**Comment by irixxxx** [comment]
fixed with 274dd51 in my repo. In with the next merge

**Comment by RobotLimeLtd** [comment]
Wow that was quick - sincere thanks and respect 👍

**Comment by irixxxx** [comment]
Well the fix was already in place. It's about 2 weeks old ;-)

**Comment by RobotLimeLtd** [comment]
Any idea when it will be included in the next nightly build?
