### ISSUE TITLE
Sonic Robo Blast 2 32X Port lagging/slowing down

### ISSUE THREAD

**Issue by K2Retro2nd** [libretro/picodrive#238]
Recently someone has created and released a port of the game Sonic Robo Blast 2 on the SEGA 32X (yes it exists now look it up) and for some reason the port is slowing down/lagging very heavily. Is there a fix planned for this so I can be able to play the new port on there? Thanks.

**Comment by irixxxx** [comment]
fixed by notaz in my repo with 4749518
