### ISSUE TITLE
RetroPie build/link issues

### ISSUE THREAD

**Issue by CloneDevil** [libretro/picodrive#24]
I updated the Retropie-Setup script, rebooted, rebuilt lr-picodrive from source, rebooted again. Then tried some Genesis games and none will load now. Goes black screen then back to game select menu.

/tmp/runcommand.log:

> /opt/retropie/emulators/retroarch/bin/retroarch: symbol lookup error: /opt/retropie/libretrocores/lr-picodrive/picodrive_libretro.so: undefined symbol: __aeabi_idiv

**Comment by CloneDevil** [comment]
Forget to mention: RaspberryPi 3 (and 8Bitdo SFC30 controller)

**Comment by joolswills** [comment]
This is fixed in https://github.com/libretro/picodrive/commit/d1dfc25952e27e5384a73ee32a4e16347a2218bb
