### ISSUE TITLE
Segmentation fault on rpi3

### ISSUE THREAD

**Issue by AlexMax** [libretro/picodrive#31]
I cannot load any ROM file with the current build of picodrive off of the armhf buildbot on my Raspberry Pi 3.  It segfaults immediately upon trying to start the emulator.  I attached a remote debugger to the retroarch process and managed to get something out of it after trying to load Sonic 3 and Knuckles...

```
Program received signal SIGSEGV, Segmentation fault.
0x72d49dee in m68k_read32 (a=10551304) at pico/memory.c:146
146     pico/memory.c: No such file or directory.
(gdb) bt
#0  0x72d49dee in m68k_read32 (a=10551304) at pico/memory.c:146
#1  0x72d80e52 in OP_0x4AB9 () at cpu/fame/famec_opcodes.h:18227
#2  0x72d9f5ba in fm68k_emulate (cycles=cycles@entry=148,
    idle_mode=idle_mode@entry=0) at cpu/fame/famec.c:905
#3  0x72d47bc6 in SekSyncM68k () at pico/pico_cmn.c:42
#4  0x72d482b4 in SekRunM68k (cyc=148) at pico/pico_cmn.c:56
#5  PicoFrameHints () at pico/pico_cmn.c:97
#6  PicoFrame () at pico/pico.c:349
#7  0x72d476a4 in retro_run () at platform/libretro/libretro.c:1224
#8  0x0001e6f4 in core_run () at core_impl.c:356
#9  0x0002e148 in runloop_iterate (sleep_ms=0x0, sleep_ms@entry=0x7ecbc1b4)
    at runloop.c:1509
#10 0x0001da64 in rarch_main (argc=<optimized out>, argv=<optimized out>,
    data=0x0) at frontend/frontend.c:122
#11 0x76ad3294 in __libc_start_main (main=0x7ecbc344, argc=1992261632,
    argv=0x76ad3294 <__libc_start_main+276>, init=<optimized out>,
    fini=0xf4d30 <__libc_csu_fini>, rtld_fini=0x76f7d408 <_dl_fini>,
    stack_end=0x7ecbc344) at libc-start.c:287
#12 0x0001b268 in _start ()
(gdb) info locals
m = 0xa10008
v = 0
vs = 0
d = <optimized out>
(gdb) info args
a = 10551304
(gdb)
```

The size of the picodrive shared library is 22,89,891 bytes, has an md5sum of `df52cd7e6b41cfebb3052e58598b2a3e` and was built on July 4th, 2016, to ensure we're talking about the same version of the library.

This bug is also really easy to recreate, so if you're interested in the output of any other gdb commands I can oblige.

**Comment by irixxxx** [comment]
@AlexMax this was long ago. I don't think this is still true. Could you please recheck this?

**Comment by irixxxx** [comment]
Closed for obsolescence. I have reports of it working on various versions of the Pi.
