### ISSUE TITLE
Rendering Issue Toe Jam & Earl

### ISSUE THREAD

**Issue by Breadwinka** [libretro/picodrive#32]
As you can see the Earthling is rendering over your Hud. Which is not correct.
![image](https://cloud.githubusercontent.com/assets/13487931/17368430/fb49c084-5961-11e6-90a1-e8884c988259.png)

**Comment by meepingsnesroms** [comment]
Is "no sprite limit" on?
If it is, turn it off.

**Comment by Breadwinka** [comment]
@meepingsnesroms Just checked and no its off. Not just eatherlings render over the hud also presents.

**Comment by Breadwinka** [comment]
This is fixed on latest stable build.

**Comment by Breadwinka** [comment]
Spoke to soon, still happening.  Wasnt happening on the one present but started on some others.

**Comment by irixxxx** [comment]
fixed with current core.
