### ISSUE TITLE
Mega CD iso with mp3

### ISSUE THREAD

**Issue by azvarel** [libretro/picodrive#45]
I am a recalbox user and realized that Mega CD games do not work iso with mp3, freeing up more space on the microsd card, which would be a great implementation.

**Comment by sergiobenrocha2** [comment]
Use Genesis Plus GX, it has OGG support.

**Comment by sergiobenrocha2** [comment]
Related to https://github.com/notaz/picodrive/issues/11

**Comment by irixxxx** [comment]
The new master branch has support for mp3 with iso, cso and cue.
The mp3 files must have a sample rate of 44100 Hz, and have 2 channels for stereo.
