### ISSUE TITLE
Sega CD RAM Cart not saving

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/picodrive#55]
See https://forums.libretro.com/t/picodrive-segacd-ram-data-getting-lost-everytime-that-game-is-loaded/10338

I can confirm that. Where's the 512 kiB save?

Enabled it in MegaCD RAM cart setting. It's not creating the file, you can format it in Sega CD bios, close RA, open it again and it's still unformatted

**Comment by gingerbeardman** [comment]
related? https://github.com/libretro/picodrive/issues/60

**Comment by gingerbeardman** [comment]
Have you checked if this is fixed in 1.92?

**Comment by wingnux** [comment]
The bug is still present on the latest version.
![Shining Force CD (U)-200905-172119](https://user-images.githubusercontent.com/70820949/92313083-aed01d80-ef9d-11ea-8acc-7a591388c4fd.png)
