### ISSUE TITLE
Feature Request: Multiplayer support

### ISSUE THREAD

**Issue by prataczak** [libretro/picodrive#56]
There are currently 7 games for Sega 32x that I am aware of that are multiplayer games. PicoDrive is the only core with 32x support. But it does not have multiplayer support. It feels like the emulation is incomplete.

If someone shows an interest in this I'm willing to put up a bounty for $25 if someone says they'll do it first.

I'm specifically interested in being able to play the multiplayer 32x games.

**Comment by irixxxx** [comment]
I recently added 4way and team player support, though only for use with 3 button pads.
