### ISSUE TITLE
No longer loading on android due to "text relocations"

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/picodrive#57]
This is exactly the same as this pcsx-rearmed bug:
[https://github.com/libretro/pcsx_rearmed/issues/116](https://github.com/libretro/pcsx_rearmed/issues/116)

**Comment by jrhardware13** [comment]
Same problems here, Android 7.1 RR fedor 5.83  lenovo Zuk Z2 , retroarch dont load the core and open content and manualy load genesis ROM show "failed to open libretto core”

**Comment by thatman84** [comment]
Any news on this issue?

**Comment by rgomesf** [comment]
notaz pushed some fixes to his repo:
https://github.com/notaz/picodrive/issues/48#issuecomment-320808989

Can it be merged into this?

**Comment by joolswills** [comment]
I think this may be related - but since the cyclone submodule update picodrive is no longer working on the RPI3 (untested on other RPI)

```
[ERROR] Failed to open libretro core: "/home/pi/temp/picodrive/picodrive_libretro.so"
[ERROR] Error(s): /home/pi/temp/picodrive/picodrive_libretro.so: unexpected reloc type 0x03
Segmentation fault
```

reverting

```
commit 66dda842eae01f47f5389b931ec9567fb0bbb6a1
Author: notaz <notasas@gmail.com>
Date:   Tue Aug 8 01:45:57 2017 +0300

    eliminate text relocations
    
    They are forbidden on newer versions of Android and iOS.
    A bit more instructions, but only for init stuff.
    No performance difference measured (basic tests only).
```

in the submodule fixes it.

referencing https://github.com/notaz/picodrive/issues/48

**Comment by psyke83** [comment]
This fixes the issue, but is there a better way? https://github.com/libretro/picodrive/pull/58

**Comment by meepingsnesroms** [comment]
Dont know why I dident close this earlier?
