### ISSUE TITLE
Feature request: CHD support

### ISSUE THREAD

**Issue by Shoegzer** [libretro/picodrive#63]
Just a feature request for chd support as has been done for many other cores such as genesis_plus_gx.  Thanks!

**Comment by Darknior** [comment]
Yes please is it possible to add it ?
So many set now are in CHD5, the best format ever ...
And you can add it like it is on other core, you have many example ...
Thanks a lot

**Comment by klepp0906** [comment]
+1 on this.

The struggle with picodrive vs genesis plus is long standing.

One has multi disc support, the other doesnt.  One has chd support, the other doesnt.   One has 32x support, the other doesnt.

Youre stuck fragmenting your collections formatting (i have half chd half bin+cue) and games like farenheit which require both scd and 32x for the 32x variant present a unique issue.  solveable only if we get some features on one side or the other to varying degrees.

**Comment by Sanaki** [comment]
Actually, as far as I know neither have working multi-disc support. But yes, lack of chd support at this point is becoming an abnormality, and for good reason.

**Comment by klepp0906** [comment]
> Actually, as far as I know neither have working multi-disc support. But yes, lack of chd support at this point is becoming an abnormality, and for good reason.
> 
> EDIT: Picodrive multidisc does work fine, it's just counterintuitive. See #114.

https://github.com/libretro/Genesis-Plus-GX/issues/209#issuecomment-636332257

**Comment by Sanaki** [comment]
If you look, I already tested that and verified it works. Just needs to be backported.

**Comment by klepp0906** [comment]
yea, i was pointing out the new commit due to your comment "neither have working multi-disc support" since genplus just had it added.

missed your having commented over there.  Its early.  coffee hasnt permeated yet ;p

**Comment by irixxxx** [comment]
I've had a look at it. Not so easy to add this, since some of the code probably needs restructuring for libchdr.
I have this on the back-backburner, so it won't come in short time.

**Comment by klepp0906** [comment]
> I've had a look at it. Not so easy to add this, since some of the code probably needs restructuring for libchdr.
> I have this on the back-backburner, so it won't come in short time.

hey, we've waited this long.  patience is a virtue/beggars cant be choosers type stuff :)

Whenever you are able to get to it everyone will be just as grateful!

**Comment by MarioKartFan** [comment]
Would love to see this added. @irixxxx has done wonders for this program but CHD support would put this over the top.

**Comment by 0x90shell** [comment]
@irixxxx Thank you for your efforts!

**Comment by irixxxx** [comment]
CHD support in 1.98
