### ISSUE TITLE
Associate with .68k files

### ISSUE THREAD

**Issue by BenMcLean** [libretro/picodrive#64]
SEGA Mega Drive & Genesis Classics on Steam provides some legal ROMs as .68k files. Unfortunately, .68k is not recognized by RetroArch as a valid filename extension for Sega Genesis ROMs. It is possible to play these (I tested this on the USA version of Sonic 3D Blast) by renaming the filename extension from .68k to .bin but I think that the ideal behavior should be to support .68k files directly as a valid filename extension for Sega Genesis ROMs. This should be a trivial change.

I posted the same issue on [Genesis Plus GX](https://github.com/libretro/Genesis-Plus-GX/issues/121).

**Comment by hizzlekizzle** [comment]
Can you load them with the core via CLI currently, or when you set the filebrowser settings to no longer 'filter unknown extensions'? If so, we can just add the extension to the core info file and it will show up in the RetroArch file browser.

**Comment by BenMcLean** [comment]
Sonic 3D Blast loads on the core currently if accessed by turning "filter unknown extensions" off. I believe adding the extension to the core info file is all that's necessary.

**Comment by hizzlekizzle** [comment]
Looks like they're already in there. Try updating your info files.

**Comment by BenMcLean** [comment]
Haha, updating my core info files did it. Thanks. Sorry to bother you with this. :)
