### ISSUE TITLE
Integer Scale

### ISSUE THREAD

**Issue by KitchUK** [libretro/picodrive#7]
While using this core for Sega CD I noticed that integer scale doesn't seem to work. The scaling seems off when using shaders.

**Comment by twinaphex** [comment]
Aspect ratio was not being set.

https://github.com/libretro/picodrive/commit/24a7ff72233aaf09dfdaa2f11c5c2bbcab236195

I'm not sure if a 4:3 aspect ratio is correct for all Genesis/Sega CD games, but give it a try anyway.

**Comment by KitchUK** [comment]
I still get fuzzy moire scanlines with integer on at core provided aspect. The crop overscan function  doesn't seem to do anything. Turning off should leave leave the image letterboxed slightly and scale the image correctly for shaders?

**Comment by KitchUK** [comment]
Btw, I'm testing with Sega CD games as I only use picodrive for these.

**Comment by CharlesBukowski** [comment]
I can confirm that this is a problem. Integer scaling will not work at resolutions higher than 640x480.

**Comment by KitchUK** [comment]
Yeah I think the problem osnwoth anything higher than 480p. Hope this can be fixed.

**Comment by irixxxx** [comment]
I believe this to be solved. @KitchUK @Patrickdroid if you're still around, could you please check again?

**Comment by irixxxx** [comment]
Tried the following settings:
- integer scaling on
- bilinear filtering off
- aspect ration core provided (set to PAR)
- video filter Grid2x
- shader handheld/bevel

everything looks evenly scaled for 320x224 (md), 256x224 (md), 320x240 (32x), 256x192 (sms) and 160x144 (gg).
So, I believe this is fixed.
