### ISSUE TITLE
Android Picodrive

### ISSUE THREAD

**Issue by LootusMaximus** [libretro/picodrive#74]
A recent update causes retroarch to crash. Android arm7

**Comment by sergiobenrocha2** [comment]
I can confirm. Android 7.0

**Comment by LootusMaximus** [comment]
I have android 5.1 and 6.0 crashes on both

**Comment by twinaphex** [comment]
update your core, it should be fixed now.

**Comment by LootusMaximus** [comment]
Yes. It works now. Good stuff
