### ISSUE TITLE
Up to 10-20 frames input lag in Blackthorne [32x]

### ISSUE THREAD

**Issue by varlamovs** [libretro/picodrive#76]
In Blackthorne for Sega 32x buttons often works only on 2nd-3rd time which result in 10-20 frames input lag while in Fusion it's only 5-10 frames. In Genesis games - only +1 frame, but in Blackthorne buttons need to be pressed like 2-3 times and I've got multiple clicks sometimes.

**Comment by AnotherLife** [comment]
Confirmed. It is disappointing because it looks good and runs at fullspeed apparently. But why is the input laggy?

**Comment by irixxxx** [comment]
Is this still the case with the current core?

**Comment by AnotherLife** [comment]
It seems fine now!

**Comment by irixxxx** [comment]
Thaknk you for the feedback...
