### ISSUE TITLE
Golden Axe Warrior (USA, Europe) (SMS) - Glitches

### ISSUE THREAD

**Issue by 00-beta-tester** [libretro/picodrive#81]
in the 1st house to save a game file, behind the man that saves the file garbage pixels, and talking with the man to save opens up the save file screen where file no. 1 & 2 are already in use with random names (no.1 AAH0, no.2 AAAAAA).
v. 1.92 eaac037
android

**Comment by irixxxx** [comment]
The support for cartridge memory mappers is lacking. It's on my back burner list, not going to touch this anytime soon.

**Comment by irixxxx** [comment]
This might be fixed with b784d4a5 in my repo, in lr-picodrive with the next merge.
