### ISSUE TITLE
Streets of Rage - UI glitch

### ISSUE THREAD

**Issue by PixelCrusader** [libretro/picodrive#83]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.3 - PicoDrive 1.92 2db9062

Black bars appear over text in the UI:

![streets of rage-180804-171338](https://user-images.githubusercontent.com/40935002/43680606-2e777510-980c-11e8-91f5-5fe083f7eb1a.png)

How it should look (Taken from Genesis Plus GX):

![streets of rage-180804-171415](https://user-images.githubusercontent.com/40935002/43680610-530d69de-980c-11e8-8bf3-8a22f24393d3.png)

**Comment by irixxxx** [comment]
will be fixed after the next PR from my repo.

**Comment by PixelCrusader** [comment]
Retroarch 1.9.0 - PicoDrive (1.965f95cd4) 

The issue has been resolved. Thanks.
