### ISSUE TITLE
Distorted/choppy audio for 32X game "Tempo" on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by c0d3h4x0r** [libretro/picodrive#91]
I'm running lr-picodrive as my Genesis and 32X emulator under RetroPie on a Raspberry Pi 3B+.

RetroPie 4.4
RetroArch 1.7.5
PicoDrive 1.92

(These are the same versions of RetroArch+PicoDrive that I use on my Win10 PC).

While it seems to emulate the audio in all other 32X games just fine on my Pi 3B+, the audio is very distorted/choppy in the game "Tempo".  I checked CPU usage during emulation by ssh'ing into the Pi and running 'top', and it reports only ~38% usage, so this doesn't seem like a CPU bottleneck.  And the problem does not repro under the same versions of RetroArch+PicoDrive on my Win10 PC.  So that leads me to suspect this may be an ARM-specific emulation bug.

Note that "Tempo" is a bit unique in that it seems to use sampled/PWM audio exclusively for audio rather than using any FM synthesis.

**Comment by c0d3h4x0r** [comment]
I was able to cure this by sliding the Raspbian system audio mixer volume way down (like below the white zone).  So it seems to me like Picodrive is playing the audio for this game particularly loud relative to other games, such that it clips and sounds terrible.

**Comment by irixxxx** [comment]
I believe this has been solved with the current master. Should be tested again and subsequently closed if fixed.

**Comment by irixxxx** [comment]
Fixed with current core
