### ISSUE TITLE
Failed to download submodules.

### ISSUE THREAD

**Issue by jdorigao** [libretro/picodrive#94]
I am not able to download the submodules, follows the link with the error:

Thank you in advance.

https://pastebin.com/raw/y4tXx5db

**Comment by emroczka** [comment]
I am having the same problem.  Looks like the host for the cpu/cyclone submodule is not available.

**Comment by irixxxx** [comment]
the current core takes its submodules from github, hence this shouldn't happen anymore.
However... the Makefile doesn't have an automatic provision to init/update submodules. Should it?

**Comment by jdorigao** [comment]
In my case it was a problem at the DNS provider and it is already solved.
