### ISSUE TITLE
[Retroarch]Picodrive does not align games properly

### ISSUE THREAD

**Issue by Fishaphrodite** [libretro/picodrive#96]
Hello,

As the title says, Picodrive's current version availiable from the "update core" does not align master system games properly, as said in this topic by cuyo01 https://forums.libretro.com/t/picodrive-not-positioning-correctly-the-screen/21708 .

I could reproduce it by loading a former version of the core I had installed (1.92 eaac037), load the game with it (I used the same game as the topic, Wonder boy III) and it was fine, after updating to the 1.92 7d6deb9 version, it was not anymore, I also could see this issue on some distributions that includes retroarch before reading about this (I was not sure where the problem lied at that point so I did not report it here).

It is the first time I ever report an issue on github so I hope I gave enough informations.

Hope you have a good day, and thanks for the hard work everyone is doing.

EDIT: I am talking about the screen being lower than it should be (which means the top is not on top and the bottom is cut out), the 8 left pixel columns however is a normal thing on the system depending on the game you play (or rather the area of the game depending on how it was coded, E.g. Zillion).

**Comment by Fishaphrodite** [comment]
I would like to add that it also seems to happen for megadrive games, even though it is somehow less visible (perhaps the offset is a fixed number so the resolution difference between master system and megadrive makes it less apparent?)

Picodrive:
![Gain Ground (Europe)-190407-122822](https://user-images.githubusercontent.com/49363070/55682233-faa60f80-5930-11e9-928f-74383c37d85f.png)
GenesisplusGX (for comparison):
![Gain Ground (Europe)-190407-122915](https://user-images.githubusercontent.com/49363070/55682234-faa60f80-5930-11e9-9a55-1ee92dc2b119.png)

**Comment by jdgleaver** [comment]
@Fishaphrodite This is fixed by PR #97 :slightly_smiling_face:
