### ISSUE TITLE
Retroarch 1.7.7 (Android) Kolibri 32 spontaneous crashes

### ISSUE THREAD

**Issue by raidoraido** [libretro/picodrive#99]
Sometimes Kolibri 32x (ROM hashes have being checked an they're all ok) just crash the emulator spontaneously and it definitely seems like the problem with this core. There is no dependencies for it by the level of the game, hardware (the problem persits on four units at least), OS (4.4-7.0), and emulator settings.

**Comment by TiredBob** [comment]
Pretty sure it's related to this issue in the main Picodrive code: https://github.com/notaz/picodrive/issues/27 which has yet to be addressed.

**Comment by irixxxx** [comment]
I've tried to reproduce this, but wasn't able to. Is this still the case with a current version?

**Comment by TiredBob** [comment]
Just noticed this reply. I'll try to update and see if this is still the
case.

**Comment by TiredBob** [comment]
> I've tried to reproduce this, but wasn't able to. Is this still the case with a current version?

Built the current version from source, tested on a Raspberry Pi 4. We were able to play the game without it crashing. Previously you could almost predict the moment it would crash in level two, and as of today I have played through level 2 at least 5 times and it no longer happens.

**Comment by irixxxx** [comment]
Ah good, thanks for testing this. Case closed, one down!
